### ISSUE TITLE
兄台在吗？

### ISSUE THREAD

**Issue by codesdt** [zhanjinfeng/minsu#1]
你好，请问你这个小程序我可以运行查看一下吗？有没有二维码我扫描看看。

**Comment by zhanjinfeng** [comment]
不好意思，这是我在上一家公司的项目，现在已经走了，后端接口信息都过期了，没有办法显示页面内容了，不过您可以看看源码，或者去我的CSDN博客看看相关的页面图片[https://blog.csdn.net/zhanjinfeng/article/details/84062322](url)

**Comment by codesdt** [comment]
打不开

Adam锋锋锋锋 <notifications@github.com> 于2019年3月27日周三 下午6:13写道：

**Comment by zhanjinfeng** [comment]
需要复制网址，在新的页面打开
